// This file contains all the config for the natural language interface

module.exports = 
{
  "operators": [
    "(([query|what]) [([equalProperty|is] ((<the> ([propertyConcept])) [([property|of] ([tankConcept]))]))])",
    "(([query|what]) [([equalNumber|is] (([number]) <plus> ([number])))])",
    "(([query|quel]) [([equalNumber|est] (([number]) <plus> ([number])))])",
    "(([query|quel]) [([equalProperty|est] ((<la> ([propertyConcept])) [([property|de] ([tankConcept]))]))])",
    "([move] (([tankConcept|tank]) [([to] ([buildingConcept|building]))]))",
    "([move] (([tankConcept|tank]) [([to] ([tankConcept|tank]))]))",
    "([move] ((<all> ([tankConcept|tank])) [([to] ([tankConcept|tank]))]))",
    "([move] ((<all> (<the> ([tankConcept|tank]))) [([to] ([tankConcept|tank]))]))",
    "(([tankConcept]) [(([tankConcept]) [conj|and] ([tankConcept]))])",
    "([stop] ([tankConcept|tank]))",
    "([stop] (<all> (<the> ([tankConcept|tank]))) )",
    "([create] (<aEnglish|a> ([tankConcept|tank])))",
    "([create] (<aEnglish|a> ([buildingConcept])))",
    "([create] (<count> ([tankConcept|tanks])))",
    "([destroy] ([tankConcept|tank]))",
    "([destroy] (<all> (<the> ([tankConcept]))))",
    "([destroy] (<all> (<the> ([buildingConcept]))))",
    "([call] ([tankConcept|tank]) (joe))",
    "([appeller] ([tankConcept|char]) francois)",
    "([deplacez] ([tankConcept|char]) ([vers] batiment))",
    "([bougez] ([tankConcept]) ([aFrench|a] batiment))",
    "(([tankConcept|char]) [conj|et] ([tankConcept]))",
    "([arreter] ([tankConcept|char]))",
    "([detruire] ([tankConcept|char]))",
    "(([i]) [wantMcDonalds|want] ([food]) ([fromM|from] ([mcdonalds])))",
    "(([i]) [wantWhitespot|want] ([food]) ([fromW|from] ([whitespot])))",
    "(<count> ([food]))",
    "(<aEnglish> ([food]))",
    "(([food]) <conj> ([food]))",
  ],
  "bridges": [
    {"bridge": "{ ...after, number: 'all' }", "id": "all", "level": 0},
    {"bridge": "{ ...after, concept: true }", "id": "the", "level": 0},
    {"bridge": "{ ...after, concept: true }", "id": "la", "level": 0},
    {"bridge": "{ marker: 'query', isQuery: true }", "id": "query", "level": 0},
    {"bridge": "{ object: after[0], ...next(operator) }", "id": "property", "level": 0},
    {"bridge": "{ value: before[0], ...next(operator) }", "id": "property", "level": 1},
    {"bridge": "{ objects: after[0], ...next(operator) }", "id": "equalProperty", "level": 0},
    {"bridge": "{ ...next(operator), objects: append(before[0], operator.objects) }", "id": "equalProperty", "level": 1},
    {"bridge": "{ objects: after[0], ...next(operator) }", "id": "equalNumber", "level": 0},
    {"bridge": "{ ...next(operator), objects: append(before[0], operator.objects) }", "id": "equalNumber", "level": 1},
    {"bridge": "{ ...next(operator), value: add(before, after), marker: before[0].marker }", "id": "plus", "level": 0},
    {"bridge": "{ ...next(operator), value: append(before, after) }", "id": "conj", "level": 0, "selector": {"match": "same", "passthrough": true, "type": "infix"}},
    {"bridge": "{ ...operator, value: append(before, operator.value) }", "id": "conj", "level": 1, "selector": {"match": "same", "passthrough": true, "type": "postfix"}},
    {"bridge": "{ ...next(operator) }", "id": "propertyConcept", "level": 0},
    {"bridge": "{ ...next(operator) }", "id": "tankConcept", "level": 0},
    {"bridge": "{ ...next(operator) }", "id": "buildingConcept", "level": 0},
    {"bridge": "{ ...next(operator), destination: after[0] }", "id": "to", "level": 0, "selector": {"type": "prefix"}},
    {"bridge": "{ ...next(operator), thing: before[0] }", "id": "to", "level": 1},
    {"bridge": "{ ...after, ...next(operator) }", "id": "move", "level": 0},
    {"bridge": "{ action: 'move', marker: 'move', thing: operator.thing, place: operator.destination }", "id": "move", "level": 1},
    {"bridge": "{ thing: after[0], ...next(operator) }", "id": "stop", "level": 0},
    {"bridge": "{ action: 'stop', marker: 'stop', thing: operator.thing }", "id": "stop", "level": 1},
    {"bridge": "{ ...next(operator), ...after }", "id": "number", "level": 0},
    {"bridge": "{ ...operator, ...after, number: operator.value }", "id": "count", "level": 0},
    {"bridge": "{ ...after, number: 1 }", "id": "aEnglish", "level": 0, "selector": {"type": "prefix"}},
    {"bridge": "{ klass: after[0], ...next(operator) }", "id": "create", "level": 0, "selector": {"type": "prefix"}},
    {"bridge": "{ action: 'create', marker: 'create', klass: operator.klass }", "id": "create", "level": 1},
    {"bridge": "{ name: after[0], ...next(operator) }", "id": "destroy", "level": 0},
    {"bridge": "{ action: 'destroy', marker: 'destroy', name: operator.name }", "id": "destroy", "level": 1},
    {"bridge": "{ ...next(operator), thing: after[0], name: after[1] }", "id": "call", "level": 0},
    {"bridge": "{ marker: 'alias', thing: operator.thing, name: operator.name }", "id": "call", "level": 1},
    {"bridge": "{ ...next(operator), after: after[0] }", "id": "vers", "level": 0},
    {"bridge": "{ ...next(operator), after: after[0] }", "id": "aFrench", "level": 0},
    {"bridge": "{ ...squish(after), thing: after[0], ...next(operator) }", "id": "deplacez", "level": 0},
    {"bridge": "{ action: 'move', marker: 'move', thing: operator.thing, place: operator.vers }", "id": "deplacez", "level": 1},
    {"bridge": "{ ...squish(after), thing: after[0], ...next(operator) }", "id": "bougez", "level": 0},
    {"bridge": "{ action: 'move', marker: 'move', thing: operator.thing, place: operator.aFrench }", "id": "bougez", "level": 1},
    {"bridge": "{ ...next(operator), thing: after[0], name: after[1] }", "id": "appeller", "level": 0},
    {"bridge": "{ marker: 'alias', thing: operator.thing, name: operator.name }", "id": "appeller", "level": 1},
    {"bridge": "{ thing: after[0], ...next(operator) }", "id": "arreter", "level": 0},
    {"bridge": "{ action: 'stop', marker: 'stop', thing: operator.thing }", "id": "arreter", "level": 1},
    {"bridge": "{ name: after[0], ...next(operator) }", "id": "detruire", "level": 0},
    {"bridge": "{ action: 'destroy', marker: 'destroy', name: operator.name }", "id": "detruire", "level": 1},
    {"bridge": "{ ...next(operator) }", "id": "food", "level": 0},
    {"bridge": "{ ...next(operator) }", "id": "mcdonalds", "level": 0},
    {"bridge": "{ ...next(operator) }", "id": "whitespot", "level": 0},
    {"bridge": "{ ...next(operator) }", "id": "i", "level": 0},
    {"bridge": "{ ...next(operator), action: 'order', items: after[0], store: after[1].from }", "id": "wantMcDonalds", "level": 0},
    {"bridge": "{ ...next(operator), action: 'order', items: after[0], store: after[1].from }", "id": "wantWhitespot", "level": 0},
    {"bridge": "{ ...next(operator), from: after[0] }", "id": "fromM", "level": 0},
    {"bridge": "{ ...next(operator), from: after[0] }", "id": "fromW", "level": 0},
  ],
  "priorities": [
  ],
  "words": {
    "+": [{"id": "plus"}],
    " ([0-9]+)": [{"id": "number", "initial": "{ value: int(group[0]) }"}, {"id": "count", "initial": "{ value: int(group[0]) }"}],
    "plus": [{"id": "plus"}],
    "tanks": [{"id": "tankConcept"}],
    "buildings": [{"id": "buildingConcept"}],
    " tank([0-9]+)": [{"id": "tankConcept", "initial": "{ id: concat('tank', group[0]) }"}],
    " char([0-9]+)": [{"id": "tankConcept", "initial": "{ id: concat('tank', group[0]) }"}],
    " building([0-9]+)": [{"id": "buildingConcept", "initial": "{ id: concat('building', group[0]) }"}],
    " batiment([0-9]+)": [{"id": "buildingConcept", "initial": "{ id: concat('building', group[0]) }"}],
    "et": [{"id": "conj"}],
    "speed": [{"id": "propertyConcept", "initial": {"name": "speed"}}],
    "vitesse": [{"id": "propertyConcept", "initial": {"name": "speed"}}],
    "position": [{"id": "propertyConcept", "initial": {"name": "position"}}],
    "cheeseburger": [{"id": "food", "initial": {"name": "cheeseburger"}}],
    "cheeseburgers": [{"id": "food", "initial": {"name": "cheeseburger"}}],
    "fries": [{"id": "food", "initial": {"name": "fries"}}],
  },
  "flatten": [
    "conj",
  ],
  "queries": [
    "what is the speed of tank1 and tank2",
    "move tank1 and tank2 to building2 and tank3 and tank4 to building3",
    "move tank1 to building1 deplacez char1 vers char2",
    "move tank1 to building2 tank2 to building1 and tank3 to building3",
    "i want 2 fries and a cheeseburger from mcdonalds",
    "i want a cheeseburger and fries from whitespot",
    "create 4 tanks",
    "move all the tanks to building3",
    "move all tanks to building3",
    "move tank1 to tank2",
    "quel est 1 + 1",
    "what is 1 + 1",
    "quel est la position de char1",
    "quel est la vitesse de char1",
    "what is the position of tank1",
    "what is the speed of tank1",
    "deplacez char1 et char2 vers batiment1",
    "move tank1 and tank2 to building2",
    "create a tank",
    "create a building",
    "destroy tank1",
    "move tank1 to tank2",
    "move tank1 and tank2 to building1",
    "deplacez char1 vers char2",
    "deplacez char1 et char2 vers bataille1",
    "move tank1 to building1",
    "deplacez char1 vers batiment1",
    "deplacez char1 vers batiment1 move tank1 to tank2",
    "call tank1 commander",
    "appeller char1 commandeur",
    "call building1 cia",
    "appeller batiment1 cia",
    "move commander to cia",
    "deplacez commandeur vers cia",
    "stop tank1",
    "arreter char1",
    "bougez char1 a batiment1",
    "bougez char1 a batiment1",
    "3 cheeseburgers and 2 fries",
    "2 fries and a cheeseburger",
    "a cheeseburger and fries",
    "a cheeseburger",
    "1 cheeseburger",
    "i want fries and a cheeseburger from mcdonalds",
    "destroy all the buildings",
    "stop all the tanks",
    "destroy all the tanks",
    "i want fries from mcdonalds",
    "i want cheeseburger and fries from whitespot",
  ],
};