export default {
  ALIAS: 'ALIAS',
  SET_POSITION: 'SET_POSITION',
  CLEAR_RESPONSE: 'CLEAR_RESPONSE',
  SET_RESPONSES: 'SET_RESPONSES',
  STARTED_QUERY: 'STARTED_QUERY',
  CREATE: 'CREATE',
  DESTROY: 'DESTROY',
  SHOW_PROPERTY: 'SHOW_PROPERTY',
  PLACE_ORDER: 'PLACE_ORDER',
  MOVE_TANK: 'MOVE_TANK',
  STOP_TANK: 'STOP_TANK',
  FIRE_TANK: 'FIRE_TANK',
  SET_CONFIG: 'SET_CONFIG',
  TICK: 'TICK',
  SET_SUBSCRIPTION: 'SET_SUBSCRIPTION',
  SET_LOGS: 'SET_LOGS',
  SET_CREDENTIALS: 'SET_CREDENTIALS'
}
