export default {
  ALIAS: 'ALIAS',
  SET_POSITION: 'SET_POSITION',
  CLEAR_RESPONSE: 'CLEAR_RESPONSE',
  SET_RESPONSES: 'SET_RESPONSES',
  STARTED_QUERY: 'STARTED_QUERY',
  CREATE: 'CREATE',
  DESTROY: 'DESTROY',
  SHOW_PROPERTY: 'SHOW_PROPERTY',
  MOVE_TANK: 'MOVE_TANK',
  STOP_TANK: 'STOP_TANK',
  FIRE_TANK: 'FIRE_TANK',
  TICK: 'TICK'
}
